# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 062bd4c51d2d9062efbbb1cd8fe1c2da3800cc55a1f805cf0f941cb6777b9b61225554ab8b4091c68dbd0946bee1eba6c90287f2916ce3bca1056555d9a359a8

test:
  secret_key_base: 6c316b534ab2d5e33fa0bd737ffa6879e0f47fab0b6841f60dbccf0a8d8d424e9f80965461560a250a23ba43e24ba6463967447bd1cfc9448c3590ef24568fda

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
